services:
  - type: web
    name: ai-vce-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.15
    disk:
      name: uploads-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
